package org.jigoku.display;

/**
 * The interface elements that are mandatory for the user interface to show.
 * Used to ensure that interfaced generated by tools expose the same elements.
 */
public interface DisplayQuestionsInterface {

	javax.swing.JTextField getAnswerDisplay();

	javax.swing.JLabel getHintDisplay();

	javax.swing.JCheckBox getHintsEnabledDisplay();

	javax.swing.JLabel getLabelSuccessRateDisplay();

	javax.swing.JLabel getLabelTestProgressDisplay();

	javax.swing.JLabel getQuestionDisplay();

	javax.swing.JProgressBar getSuccessRateDisplay();

	javax.swing.JProgressBar getTestProgressDisplay();

	javax.swing.JLabel getTranslationDisplay();

	javax.swing.JCheckBox getTranslationsEnabledDisplay();

	void answerKeyTyped(final java.awt.event.KeyEvent evt);
}
