package org.jigoku;

/**
 * The interface elements that are mandatory for the user interface to show.
 * Used to ensure that interfaced generated by tools expose the same elements.
 */
public interface TestDisplayInterface {

	javax.swing.JTextField answer = null;
	javax.swing.JLabel hint = null;
	javax.swing.JCheckBox hintsEnabled = null;
	javax.swing.JLabel labelSuccessRate = null;
	javax.swing.JLabel labelTestProgress = null;
	javax.swing.JLabel question = null;
	javax.swing.JProgressBar successRate = null;
	javax.swing.JProgressBar testProgress = null;
	javax.swing.JLabel translation = null;
	javax.swing.JCheckBox translationsEnabled = null;

	void answerKeyTyped(final java.awt.event.KeyEvent evt);

}
