package org.jigoku;



public class TestDisplay extends javax.swing.JFrame implements TestDisplayInterface {
	public static final long serialVersionUID = 1L;
	
    protected TestDisplay () {
    	//used only for unittest
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    protected void initComponents() {
    	question = new javax.swing.JLabel();
    	hintsEnabled = new javax.swing.JCheckBox();
        hint = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        translationsEnabled = new javax.swing.JCheckBox();
        translation = new javax.swing.JLabel();
        testProgress = new javax.swing.JProgressBar();
        labelTestProgress = new javax.swing.JLabel();
        successRate = new javax.swing.JProgressBar();
        labelSuccessRate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hintsEnabled.setText("hints");
        hintsEnabled.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hintsEnabled.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hintsEnabled.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hintsEnabledPropertyChange(evt);
            }
        });

        hint.setBackground(new java.awt.Color(255, 255, 255));
        hint.setText("Ten (things)");

        answer.setText("jTextField1");
        answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                answerKeyTyped(evt);
            }
        });

        translationsEnabled.setText("translation");
        translationsEnabled.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        translationsEnabled.setMargin(new java.awt.Insets(0, 0, 0, 0));

        translation.setText("jLabel2");

        testProgress.setMaximum(50);
        testProgress.setValue(27);

        labelTestProgress.setText("Test Progress");

        question.setText("jLabel1");

        successRate.setBackground(new java.awt.Color(255, 102, 51));
        successRate.setForeground(new java.awt.Color(204, 255, 0));
        successRate.setMaximum(100);
        successRate.setValue(100);

        labelSuccessRate.setText("Success rate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hintsEnabled)
                        .addGap(6, 6, 6)
                        .addComponent(hint, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(translationsEnabled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(translation, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                    .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(labelSuccessRate)
                    .addComponent(successRate, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(labelTestProgress)
                    .addComponent(testProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hintsEnabled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(translationsEnabled)
                    .addComponent(translation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSuccessRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(successRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTestProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>                        

    protected void hintsEnabledPropertyChange(java.beans.PropertyChangeEvent evt) {                                            
        hint.setVisible(hintsEnabled.isSelected());
    }
        
    public void answerKeyTyped(java.awt.event.KeyEvent evt) {
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDisplay().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    public javax.swing.JTextField answer;
    public javax.swing.JLabel hint;
    public javax.swing.JCheckBox hintsEnabled;
    public javax.swing.JLabel labelSuccessRate;
    public javax.swing.JLabel labelTestProgress;
    public javax.swing.JLabel question;
    public javax.swing.JProgressBar successRate;
    public javax.swing.JProgressBar testProgress;
    public javax.swing.JLabel translation;
    public javax.swing.JCheckBox translationsEnabled;
    // End of variables declaration                   

}
